# -*-coding:Utf-8 -*
""" Parameters """

LIST_ALL_TITLES_CHANGED:bool = True
ALL_TITLES_CHANGED_FILE_NAME_BEFORE:str = "ALL_TITLES_CHANGED_FILE_NAME_before.txt"
ALL_TITLES_CHANGED_FILE_NAME_AFTER:str = "ALL_TITLES_CHANGED_FILE_NAME_after.txt"

PATH_OF_FILE_LISTING_LAST_M3U_FILE_LOADED = "last_m3u_file_loaded.txt"
