COLUMNS_NAMES_TO_REMOVE = [
    "Unique ID",
    "Code Dico & Code Arborescence",
    "MemoEasy",
    "Niveau Arborescence",
    "Code Arborescence",
    "Nom Arborescence",
    "Code Dico",
    "Type Document",
    "Tranche",
    "Phase",
    "Désignation Phase",
    "Work Package",
    "WorkPackageLeader",
    "Jalon Contractuel",
    "Date Jalon Contractuel",
    "Commentaires Internes",
    "Commentaires MOE",
    "Référentiel",
    "Jalon GUIDE",
    "Work Product",
    "ID Macrotache",
    "% Macro Tache",
    "Montant",
    "Activité Planning",
    "Date Planning",
    "Lien Doc-Planning",
    "Baseline Livraison",
    "Previous Forecast Livraison",
    "À confirmer Livraison",
    "Durée Livraison 1è Version & Acceptation",
    "GCONF",
    "Jalon Fourniture",
    "Nb de commentaires bloquants encore ouverts",
    "Document Supprimé",
    "Dernière Soumission ",
    "Document technique (Yes/No)",
    "Confidentialité Document",
    "Référence SNCF",
    "ATS+/Nexteo",
    "% Avancement DML",
    "Dernier statut Document",
    "Version avec dernier statut",
    "FILTERED OR NOT",
    "IS LAST VERSION",
    "IS FIRST VERSION",
    "IS FIRST ACCEPTATIONTBDLAST REFUSAL",
    "VERSION & REVISION",
    "CHROMATIC DISCRIMINANT",
    "Numeros  SNCF Mobilités \nn°10-5969 632 \nà\nn°10-5970-637",
    "Statut acceptation",
    "Date Acceptation",
    "Baseline FA",
]
