from generatecfxhistory.role import SubSystem

other_projects_release_subsystem_mapping: dict[SubSystem, list[str]] = {
    SubSystem.TBD: [""],
}


next_atsp_release_subsystem_mapping: dict[SubSystem, list[str]] = {
    SubSystem.TCR3: ["S003_Component TCR3", "TCR3"],
    SubSystem.RESEAU: ["Réseau", "Commutateur", "pare-feu"],
    SubSystem.SW: [
        "Component MES",
        "Component PAE",
        "Component PAS",
        "Applicatif PAS",
        "S002_Subsystem Automatic Train Control",
        "Module Application PAS",
        "Module Application PAL",
        "S003_Component PAL",
        "S003_Component Atelier de Développement Logiciel",
        "S003_Component Canevas",
        "S004_Module PAI",
    ],
    SubSystem.SUBSYS: [
        "CDB",
        "MDT",
        "Eurobalise",
        "Tiroir Calculateur",
        "Transition par balise",
        "Odotachy",
        "EVC/DMI/JRU",
        "Logiciel de service",
        "Compte à rebour",
        "S003_Component Niveau 3 - Sol",
        "S003_Component Niveau 3 - Bord",
        "S003_Component PPN",
        "S004_Module GenTel",
    ],
    SubSystem.TRACY: ["Cyclos"],
    SubSystem.ATS: [
        "Automatic Train Supervision",
        "S001_System ATSP",
        "Tube",
        "SIMEV",
        "SIFOR",
        "Foxtrot",
        "S003_Component Master",
        "S004_Module Package AD",
        "Module Master",
        "S003_Component Package AD",
        "ATS",
        "Atelier de paramétrage",
        "S002_Subsystem SECU IHM",
        "S002_Subsystem RTO",
        "Serveur d'authentification",
        "Boitier PERLE Signalisation NT Durcisssement",
    ],
    SubSystem.COC_DE: ["S002_Subsystem Invariants", "Invariants", "Paramètres", "S003_Component SMT3"],
    SubSystem.TCM_TC: ["SIMECH", "Gumps", "Outils", "XT_OT", "S003_Component TU"],
    SubSystem.RADIO: ["RADIO", "Baie Centrale Radio"],
    SubSystem.ATS_EVIDEN: ["COEUR CK", "FGPT", "MES SIL2"],
    SubSystem.ADONEM: ["ADONEM"],
    SubSystem.TCM_TM1: ["Plateforme", "Usine"],
    SubSystem.TCM_TM2: ["Site"],
    SubSystem.SYSTEME: [
        "S001_System Système NExTEO ATC",
        "S001_System Système NExTEO",
        "Performances du système",
        "Interfaces Signalisation",
        "Interfaces Voie",
        "S003_Component Inferfaces Matériel Roulant",
    ],
    SubSystem.ITF_MR: ["S001_System Système NExTEO ATC", "S002_Subsystem Interfaces_NEXTEO"],
    SubSystem.PROJET: ["Management du projet", "Mise en Service Commerciale NExTEO", "Module Formulaires COVASEC"],
    SubSystem.ATC_MANAGER: ["Matériels complémentaires"],
    SubSystem.SAF: ["Fiabilité"],
    SubSystem.INSTALLATION: ["SBL", "S004_Module Installation"],
}
